#!/usr/bin/expect -f

set ip 192.168.10.91
set user danny
set password hsae**bsp123
set timeout 5
spawn ssh $user@$ip
expect {
	"*yes/no" {send "yes\r"; exp_continue}
	"*password:" {send "$password\r"}
}
interact
 



